[package]
name = "meilisearch-tasks"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
chrono = { version = "0.4.19", features = ["serde"] }
heed = { git = "https://github.com/Kerollmops/heed", tag = "v0.12.1", default-features = false, features = ["lmdb", "sync-read-txn"] }
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dev-dependencies]
mockall = "0.10.2"
nelson = { path = "../../nelson" }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.2.0"
